field: 7147aec6-4c49-4d7c-be79-3e9e57b5991f # Office
fieldLayouts:
  e15266e1-6498-405d-863d-7b38b9a9f002:
    tabs:
      -
        elements:
          -
            fieldUid: 320b16b1-359a-4ce8-9f21-859e91a01a3f # Caption
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  320b16b1-359a-4ce8-9f21-859e91a01a3f: # Caption
    contentColumnType: text
    fieldGroup: null
    handle: caption
    instructions: ''
    name: Caption
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: header
name: Header
sortOrder: 1
