contentColumnType: string
fieldGroup: 9efbeade-59dd-4c2d-89d4-8d38a46bfc50 # Common
handle: logotype
instructions: ''
name: Logotype
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - image
    - xml
  defaultUploadLocationSource: 'volume:febc00ea-0cb7-4ada-9e01-ca7a01332cba' # Logotypes
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: thumbs
  restrictFiles: '1'
  selectionLabel: ''
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:febc00ea-0cb7-4ada-9e01-ca7a01332cba' # Logotypes
  singleUploadLocationSubpath: ''
  source: null
  sources: '*'
  targetSiteId: null
  useSingleFolder: true
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
