contentColumnType: string
fieldGroup: 9efbeade-59dd-4c2d-89d4-8d38a46bfc50 # Common
handle: menu
instructions: ''
name: Menu
searchable: false
settings:
  contentTable: '{{%matrixcontent_menu}}'
  maxBlocks: '7'
  minBlocks: '1'
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
