contentColumnType: string
fieldGroup: 9efbeade-59dd-4c2d-89d4-8d38a46bfc50 # Common
handle: process
instructions: ''
name: Process
searchable: false
settings:
  contentTable: '{{%matrixcontent_process}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
