enableVersioning: true
handle: homePage
name: 'Home Page'
propagationMethod: all
siteSettings:
  1e00f3c3-88a4-4c2e-bee0-6f7d5cb70a10: # Flare
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: __home__
type: single
